chore: add JF prefix to docker base [ESUSDLC-993]
Paymentology/pr-size-labeler pull request #2
Opened 2024-11-06 12:05 UTC by yd-paymentology

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description
Add JF prefix, so we don't hit docker rate limits

## Notes to Reviewer
This will solve rate limits issue, however will increase data transfer

## How to test
Update Github workflow with the branch name

## Link to issues addressed
- https://paymentology.atlassian.net/browse/ESUSDLC-993

2024-11-06 13:05 UTC, lbornov2paymentology requested changes

2024-11-06 13:05 UTC, lbornov2paymentology commented on Dockerfile
> +FROM paymentology.jfrog.io/pt-docker-virtual-thirdparty/alpine:3.15
I would make this a build-arg

2024-11-08 10:17 UTC, mpdred commented on Dockerfile
> +FROM paymentology.jfrog.io/pt-docker-virtual-thirdparty/alpine:3.15
no need to overcomplicate things for a small repo
sticking with the fixed base image keeps it simple and reduces the chance for surprises

2024-11-08 16:15 UTC, dhrapson commented on .github/workflows/labeler.yml
> -name: labeler
Its a shame to remove this file since the tests for this repository are now no longer self-contained.
I would presume we did this because adding the build arg means this workflow has to execute on self-hosted and this public repo cannot do that.

This is another strong argument for us to internalise the fork & test against real cached repos.

Approving for now though to alleviate the rate limiting issue.

2024-11-08 16:15 UTC, dhrapson approved these changes

2024-11-08 16:27 UTC, merged